#define PLACES 3
#define CONTROLS_PER_PLACE 3

#define SHM_INDEX_WAITING_NUMBER 0
#define SHM_SIZE_WITHOUT_PLACES 1

#define MSG_QUEUE_FAN 'F'
#define MSG_EMPTY_CONTROL 1
#define MSG_EMPTY_CONTROL_FOR_WAITING 2
#define MSG_QUEUE_FAN_TYPES 2
#define MSG_CONTROL_TAKEN -1

#define MSG_QUEUE_WORKER 'W'

#define MSG_QUEUE_CONTROL 'C'
#define MSG_INITIATE_CONTROL = 1
#define MSG_QUEUE_CONTROL_TYPES 1

#define K 1000